name: Deploy to Server Docker

on:
  push:
    branches:
      - main  # Trigger on main branch push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t roadstat .
          docker save roadstat -o $HOME/roadstat.tar

      - name: Verify .tar file
        run: |
          if [ -f "$HOME/roadstat.tar" ]; then
            echo "File exists and is ready for transfer."
          else
            echo "File does not exist or was not created correctly."
            exit 1
          fi

      - name: Transfer image to server using rsync
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/aws_key
          chmod 600 /tmp/aws_key
          rsync -avz -e "ssh -i /tmp/aws_key -o StrictHostKeyChecking=no" $HOME/roadstat.tar ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:~/roadstat.tar

      - name: Deploy on Server
        env:
          HOST: ${{ secrets.AWS_HOST }}
          USER: ${{ secrets.AWS_USERNAME }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          # Write SSH key to a temporary file and set permissions
          echo "${SSH_KEY}" > /tmp/aws_key
          chmod 600 /tmp/aws_key
          
          # SSH to the remote server and run the deployment commands
          ssh -i /tmp/aws_key -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Load Docker image from the tar file
            docker load -i ~/roadstat.tar

            # Stop and remove any existing container with the same name
            docker rm -f roadstat || true

            # Run the container with ports exposed
            docker run -d --name roadstat -p 3000:3000 -p 5173:5173 roadstat
          EOF
