name: Build and Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger on main branch push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for advanced features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/roadstat .
          # Tag image with commit SHA (ensure GITHUB_SHA is available)
          docker tag ${{ secrets.DOCKER_USERNAME }}/roadstat:latest ${{ secrets.DOCKER_USERNAME }}/roadstat:${{ github.sha }}

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/roadstat:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/roadstat:${{ github.sha }}

      # Step 6: Deploy on AWS Server
      - name: Deploy on AWS Server
        env:
          HOST: ${{ secrets.AWS_HOST }}
          USER: ${{ secrets.AWS_USERNAME }}
          SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          # SSH into the AWS server and deploy the Docker image
          echo "${{ secrets.AWS_SSH_KEY }}" > /tmp/aws_key
          chmod 600 /tmp/aws_key
          ssh -i /tmp/aws_key -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Pull the Docker image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/roadstat:latest
            
            # Stop and remove any existing container
            docker rm -f roadstat || true

            # Run the new Docker container
            docker run -d --name roadstat -p 3000:3000 -p 5173:5173 ${{ secrets.DOCKER_USERNAME }}/roadstat:latest
          EOF
