name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 519842164857.dkr.ecr.ap-south-1.amazonaws.com

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          docker build -t roadlorry .
          docker tag roadlorry:latest 519842164857.dkr.ecr.ap-south-1.amazonaws.com/roadlorry:latest
          docker push 519842164857.dkr.ecr.ap-south-1.amazonaws.com/roadlorry:latest

      # Step 5: Update ECS service with the new task definition
      - name: Update ECS service
        run: |
          # Register a new task definition revision with the updated image
          NEW_TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition roadlorry --query 'taskDefinition' | jq '.containerDefinitions[0].image="519842164857.dkr.ecr.ap-south-1.amazonaws.com/roadlorry:latest" | {containerDefinitions, family, taskRoleArn, executionRoleArn, networkMode, requiresCompatibilities, cpu, memory}')
          echo "$NEW_TASK_DEFINITION" > new-task-definition.json
          aws ecs register-task-definition --cli-input-json file://new-task-definition.json

          # Update ECS service to use the new task definition revision
          LATEST_TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition roadlorry --query 'taskDefinition.taskDefinitionArn' --output text)
          aws ecs update-service --cluster arn:aws:ecs:ap-south-1:519842164857:cluster/DevCluster --service devclusterservice --task-definition "$LATEST_TASK_DEF_ARN"
